### ISSUE TITLE
Cannot run coffeem on Windows

### ISSUE THREAD

**Issue by gabbsmo** [alonbardavid/coffee-script-mapped#3]
I have installed coffee-script-mapped globally on Windows 7 64-bit. However, coffeem is not recognized as a valid command in cmd. I suspect it's not included in path, if so where do I find the binary so I can add it manually? If this is true, consider this a feature request.

**Comment by alonbardavid** [comment]
as with all npm modules (that have a bin script), you can find it either in your workspace\node_modules.bin\coffeem.cmd or (if installed globaly) in C:\Users<username>\AppData\Roaming\npm\ .

I installed it globally in my own windows 7 64 bit and it works. Are you sure that:
- you installed it with -g (can you check if it's in C:\Users<username>\AppData\Roaming\npm\ )
- is C:\Users<username>\AppData\Roaming\npm\  in your enviorment path? (you can check it by typing echo %PATH%.

if both are true, it seems very wierd, can you copy paste the log when you run:
`npm install coffee-script-mapped -g`

**Comment by alonbardavid** [comment]
"Realised there was no windows executable, move along."

what do you mean? (did you try running it with child_process.spawn? if so, it doesn't work very well with windows, I suggest you try running spawn and passing {env:process.env}

**Comment by gabbsmo** [comment]
was missing the -g switch. first day on node. sorry about that.
