### ISSUE TITLE
Using coffee-script-mapped module with the require statement

### ISSUE THREAD

**Issue by ashimaathri** [alonbardavid/coffee-script-mapped#4]
Is it possible to use the coffee-script-mapped module like this

```
require('coffee-script-mapped')
```

in place of

```
require('coffee-script')
```

And still have the line numbers in the the errors mapped back to the coffeescript files?

Thanks,
Ashima

**Comment by alonbardavid** [comment]
Sure. Just remember that you still need to install a coffee-script package, since coffee-script-mapped doesn't come built-in with one.
