### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by webjay** [alonbardavid/coffee-script-mapped#6]
I'm on a Mac and installed coffee-script-mapped like this:

```
npm install -g coffee-script-mapped
```

When I run `coffeem app.coffee` I get this error:

```
env: node\r: No such file or directory
```

If I open `/usr/local/share/npm/bin/coffeem` I see `<CR>` at the end of the first two lines.

```
#!/usr/bin/env node<CR>
<CR>
```

If I replace `<CR>` with a newline it works.

**Comment by alonbardavid** [comment]
sorry I don't have a linux based computer to make tests for this at the moment. I've updated the repository with removing the Carddige return.
can you check and see if the new version (published to npm) fixes your issue?

**Comment by webjay** [comment]
yep, it works, thanks.
