### ISSUE TITLE
TypeError "Arguments to path.resolve must be strings"

### ISSUE THREAD

**Issue by godmar** [alonbardavid/coffee-script-mapped#7]
I'm using node v0.10.26 and coffee-script-mapped 0.1.5 with coffee-script 1.7.1

Whenever an error occurs, I'm getting:

path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at mapSourcePosition (/var/www/services/360license/node_modules/coffee-script-mapped/lib/source-map-support.js:50:36)
    at wrapCallSite (/var/www/services/360license/node_modules/coffee-script-mapped/lib/source-map-support.js:88:20)
    at /var/www/services/360license/node_modules/coffee-script-mapped/lib/source-map-support.js:124:26
    at Array.map (native)
    at prepareStackTrace (/var/www/services/360license/node_modules/coffee-script-mapped/lib/source-map-support.js:123:24)
    at Function.Error.prepareStackTrace (/var/www/services/360license/node_modules/coffee-script-mapped/lib/coffee-script-mapped.js:50:20)
    at process.handleUncaughtExceptions (/var/www/services/360license/node_modules/coffee-script-mapped/lib/source-map-support.js:130:23)
    at process.EventEmitter.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)

The error occurs because 'originalPosition.source' is null. If I modify your code like so:

  // Resolve the source URL relative to the URL of the source map
  if (sourceMap) {
    var originalPosition = sourceMap.map.originalPositionFor(position);
    console.log("position");
    console.dir(position);
    console.log("originalPosition as returned by sourceMap.map.originalPositionFor(position)");
    console.dir(originalPosition);
    originalPosition.source = path.resolve(path.dirname(sourceMap.url), originalPosition.source);
    return originalPosition;
  } else {
    return position;
  }

I get:

position
{ source: '/var/www/services/360license/src/server/bin.coffee',
  line: 16,
  column: 4 }
originalPosition as returned by sourceMap.map.originalPositionFor(position)
{ source: null, line: null, column: null, name: null }

path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^

The file in question does not have a line 16, it has only 14 lines:

$ wc /var/www/services/360license/src/server/bin.coffee
 14  40 358 /var/www/services/360license/src/server/bin.coffee

(A past version had 16 lines. Caching?)

My main script is this:

$ cat bin/server 
# !/usr/bin/env node

require('coffee-script-mapped')
require('../src/server/bin')

Any hints on how to debug this? Since it's in the uncaught exception handler, I have no idea what's causing the original exception.

All I did was "npm install coffee-script-mapped", "npm install coffee-script"

I copied the setup from another project in which it was working.

Thanks.

**Comment by godmar** [comment]
PS: commenting out this:

```
//Error.prepareStackTrace = prepareStackTrace;
```

fixes it. The line numbers and error are now correct:

TypeError: number is not a function
  at SummonStatWatcher.start (/var/www/services/360license/src/server/360license.coffee:21:24)
  at Object.<anonymous> (/var/www/services/360license/src/server/bin.coffee:10:3)

That's the correct error.

This confuses me. How can the line numbers be correct without coffee-script-mapped? I thought I needed it to get the line numbers correct?  Do I need coffee-script-mapped at all now?

Aside: The line 16 makes sense if I look at bin.js (compiled from bin.coffee), then indeed it's in the stack trace.  However, I'm using the on-the-fly compilation method (which I thought it what 'require('coffee-script-mapped')' does.

I find this utterly confusing and quite frankly a waste of time. I wish node/coffeescript worked out of the box. Thanks for listening.

From a software engineering point of view, you might want to handle a failure in the source map consumer where the .source property comes back as null. I don't know what it indicates, but you could catch it and flag it, perhaps like so:

```
// Resolve the source URL relative to the URL of the source map
if (sourceMap) {
   var originalPosition = sourceMap.map.originalPositionFor(position);
   if (originalPosition.source) {
      originalPosition.source = path.resolve(path.dirname(sourceMap.url), originalPosition.source);
      return originalPosition;
   } else
      return position;
} else {
   return position;
}
```

This works for me and shows the error correctly.

**Comment by alonbardavid** [comment]
looks like coffe-script 1.7 fixed some issues (and also changed how you work with coffeescript).
The result is not 100% the same, but using "coffee-script/register" provides a good enough solution.

If anyone start a new project I would suggest not using this package and instead use "coffee-script/register" directly.

I've fixed this project to just call "coffee-script/register" if the coffee-script version provided is above 1.7 .

I hope this is good enough.
